starcraft-alp-gmm-ppo:
  run: PPO-curriculum
  checkpoint_freq: 100
  checkpoint_at_end: true
  local_dir: ray_results
  stop:
    timesteps_total: 1000000
  config:
    seed: 0
    framework: torch
    callbacks: PvEMetrics

    teacher_config:
      name: alp-gmm
      num_agents: [2, 6, 8]
      gmm_fitness_func: aic
      warm_start: false
      nb_em_init: 1
      fit_rate: 250
      alp_window_size: 200
      random_task_ratio: 0.2
      nb_bootstrap: null
      initial_dist: null

    env: starcraft_curriculum
    env_config:
      map_name: 8m
      heuristic_ai: true
      heuristic_rest: true
      max_num_agents: 8
      in_evaluation: false

    num_workers: 1
    num_cpus_for_driver: 1
    num_envs_per_worker: 1
    num_cpus_per_worker: 1
    num_gpus: 1
    num_gpus_per_worker: 0
    evaluation_num_workers: 1
    evaluation_interval: 5  # iterations
    evaluation_duration: 20
    evaluation_duration_unit: episodes
    evaluation_parallel_to_training: true
    disable_env_checking: true

    evaluation_config:
      env_config:
        map_name: 8m
        max_num_agents: 8
        in_evaluation: true

    model:
      custom_model: action_mask_model

    multiagent:
      policies: ["shared_policy"]
      policy_mapping_fn: parameter_sharing
      policies_to_train: ["shared_policy"]
